#!/bin/sh

restore='\033[0m'
KERNEL_DIR=$PWD
blue='\033[0;34m'

export ARCH=arm64
export SUBARCH=arm64

echo "${blue}"
echo "***********************************************"
echo "                 Cleaning Up                   "
echo "***********************************************"
rm -f $KERNEL_DIR/arch/arm64/boot/Image.gz-dtb
rm -f $KERNEL_DIR/arch/arm64/boot/Image.gz
rm -f $KERNEL_DIR/arch/arm64/boot/Image
rm -f $KERNEL_DIR/output/Image.gz-dtb
rm -f $KERNEL_DIR/output/Image.gz
$clean make clean && make mrproper
