#ifndef _CUST_BATTERY_METER_H
#define _CUST_BATTERY_METER_H

#include <mach/mt_typedefs.h>

#define SOC_BY_HW_FG
#define HW_FG_FORCE_USE_SW_OCV
#define R_BAT_SENSE 4
#define R_I_SENSE 4
#define R_CHARGER_1 330
#define R_CHARGER_2 39
#define TEMPERATURE_T0             110
#define TEMPERATURE_T1             0
#define TEMPERATURE_T2             25
#define TEMPERATURE_T3             50
#define TEMPERATURE_T              255
#define FG_METER_RESISTANCE	0
#define Q_MAX_POS_50			2628
#define Q_MAX_POS_25			2660
#define Q_MAX_POS_0			2544
#define Q_MAX_NEG_10			2404
#define Q_MAX_POS_50_H_CURRENT		2696
#define Q_MAX_POS_25_H_CURRENT		2706
#define Q_MAX_POS_0_H_CURRENT		2430
#define Q_MAX_NEG_10_H_CURRENT		1763
#define OAM_D5		 1
#define CHANGE_TRACKING_POINT
#ifdef CONFIG_MTK_HAFG_20
#define CUST_TRACKING_POINT 0
#else
#define CUST_TRACKING_POINT 1
#endif
#define CUST_R_SENSE 10
#define CUST_HW_CC 0
#define AGING_TUNING_VALUE	103
#define CUST_R_FG_OFFSET    0
#define OCV_BOARD_COMPESATE	0
#define R_FG_BOARD_BASE		1000
#define R_FG_BOARD_SLOPE	1000
#define CAR_TUNE_VALUE		100
#define CURRENT_DETECT_R_FG	10
#define MinErrorOffset       1000
#define FG_VBAT_AVERAGE_SIZE 18
#define R_FG_VALUE			10
#define DIFFERENCE_HWOCV_RTC		30
#define DIFFERENCE_HWOCV_SWOCV		10
#define DIFFERENCE_SWOCV_RTC		10
#define MAX_SWOCV			3
#define DIFFERENCE_VOLTAGE_UPDATE	20
#define AGING1_LOAD_SOC			70
#define AGING1_UPDATE_SOC		30
#define BATTERYPSEUDO100		95
#define BATTERYPSEUDO1			4
#define Q_MAX_BY_SYS
#define Q_MAX_SYS_VOLTAGE		3200
#define SHUTDOWN_GAUGE0
#define SHUTDOWN_GAUGE1_XMINS
#define SHUTDOWN_GAUGE1_MINS		60
#define SHUTDOWN_SYSTEM_VOLTAGE		3200
#define CHARGE_TRACKING_TIME		60
#define DISCHARGE_TRACKING_TIME		10
#define RECHARGE_TOLERANCE		10
#define MAX_HWOCV			5
#define MAX_VBAT			90
#define DIFFERENCE_HWOCV_VBAT		30
#define CUST_POWERON_DELTA_CAPACITY_TOLRANCE	40
#define CUST_POWERON_LOW_CAPACITY_TOLRANCE		5
#define CUST_POWERON_MAX_VBAT_TOLRANCE			90
#define CUST_POWERON_DELTA_VBAT_TOLRANCE		30

#ifdef CONFIG_MTK_DISABLE_POWER_ON_OFF_VOLTAGE_LIMITATION
#define FIXED_TBAT_25
#endif

#define VBAT_NORMAL_WAKEUP		3600
#define VBAT_LOW_POWER_WAKEUP		3500
#define NORMAL_WAKEUP_PERIOD		5400
#define LOW_POWER_WAKEUP_PERIOD		300
#define CLOSE_POWEROFF_WAKEUP_PERIOD	30
#define INIT_SOC_BY_SW_SOC
#define MTK_ENABLE_AGING_ALGORITHM
#define MD_SLEEP_CURRENT_CHECK

#endif
